name: on-push
run-name: on push to main

on:
  push:
    branches:
      - main

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-citations:
    # skip first run because nothing enabled or setup yet
    if: github.run_number != 1
    uses: ./.github/workflows/update-citations.yaml

  update-jobs:
    needs: update-citations
    uses: ./.github/workflows/update-jobs.yaml

  build-site:
    needs: update-citations
    uses: ./.github/workflows/build-site.yaml
