name: update-jobs
run-name: update job listings

on:
  # run when called from another workflow
  workflow_call:
    inputs:
      open-pr:
        type: boolean
    outputs:
      changed:
        value: ${{ jobs.update-jobs.outputs.changed }}

  # run if user manually requests it
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

env:
  FORCE_COLOR: true

jobs:
  update-jobs:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Debug dump
        uses: crazy-max/ghaction-dump-context@v2

      - name: Checkout branch contents
        if: github.event.action != 'closed'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.head_ref }}

      - name: Set up Python
        if: github.event.action != 'closed'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: "**/requirements.txt"

      - name: Install Python packages
        if: github.event.action != 'closed'
        run: |
          python -m pip install --upgrade --requirement ./_cite/requirements.txt

      - name: SSH debug
        if: runner.debug == '1'
        uses: mxschmitt/action-tmate@v3

      - name: Build updated job listings
        if: github.event.action != 'closed'
        run: python _cite/jobs.py
        timeout-minutes: 15

      - name: Check if jobs changed
        if: github.event.action != 'closed'
        id: changed
        uses: tj-actions/verify-changed-files@v18
        with:
          files: |
            _data/jobs.yaml

      - name: Pull latest changes and handle conflicts
        if: |
          github.event.action != 'closed' &&
          steps.changed.outputs.files_changed == 'true'
        run: |
          git stash push -m "Stash job updates"
          git pull --rebase origin ${{ github.ref_name }}
          git stash pop || echo "No conflicts or stash already applied"

      - name: Commit updated jobs to branch
        if: |
          github.event.action != 'closed' &&
          steps.changed.outputs.files_changed == 'true'
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update job listings automatically"

    outputs:
      changed: ${{ steps.changed.outputs.files_changed || false }}
